[537] updated .toString()s methods.
They will now return "Non-generated Reflection/Flare" in case the .reflect() method hadn't been called yet. This is to prevent an undefined Reference to show up on the terminal even though it's incorrect.